version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    container_name: nodejs-server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    container_name: reactjs-client
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
    links:
      - server
